/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CarbonFootprintTracking } from "./CarbonFootprintTracking";
import { CarbonFootprintTrackingCountArgs } from "./CarbonFootprintTrackingCountArgs";
import { CarbonFootprintTrackingFindManyArgs } from "./CarbonFootprintTrackingFindManyArgs";
import { CarbonFootprintTrackingFindUniqueArgs } from "./CarbonFootprintTrackingFindUniqueArgs";
import { DeleteCarbonFootprintTrackingArgs } from "./DeleteCarbonFootprintTrackingArgs";
import { CarbonFootprintTrackingService } from "../carbonFootprintTracking.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => CarbonFootprintTracking)
export class CarbonFootprintTrackingResolverBase {
  constructor(
    protected readonly service: CarbonFootprintTrackingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "CarbonFootprintTracking",
    action: "read",
    possession: "any",
  })
  async _carbonFootprintTrackingsMeta(
    @graphql.Args() args: CarbonFootprintTrackingCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [CarbonFootprintTracking])
  @nestAccessControl.UseRoles({
    resource: "CarbonFootprintTracking",
    action: "read",
    possession: "any",
  })
  async carbonFootprintTrackings(
    @graphql.Args() args: CarbonFootprintTrackingFindManyArgs
  ): Promise<CarbonFootprintTracking[]> {
    return this.service.carbonFootprintTrackings(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => CarbonFootprintTracking, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "CarbonFootprintTracking",
    action: "read",
    possession: "own",
  })
  async carbonFootprintTracking(
    @graphql.Args() args: CarbonFootprintTrackingFindUniqueArgs
  ): Promise<CarbonFootprintTracking | null> {
    const result = await this.service.carbonFootprintTracking(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CarbonFootprintTracking)
  @nestAccessControl.UseRoles({
    resource: "CarbonFootprintTracking",
    action: "delete",
    possession: "any",
  })
  async deleteCarbonFootprintTracking(
    @graphql.Args() args: DeleteCarbonFootprintTrackingArgs
  ): Promise<CarbonFootprintTracking | null> {
    try {
      return await this.service.deleteCarbonFootprintTracking(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
