/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DocumentDatabase } from "./DocumentDatabase";
import { DocumentDatabaseCountArgs } from "./DocumentDatabaseCountArgs";
import { DocumentDatabaseFindManyArgs } from "./DocumentDatabaseFindManyArgs";
import { DocumentDatabaseFindUniqueArgs } from "./DocumentDatabaseFindUniqueArgs";
import { DeleteDocumentDatabaseArgs } from "./DeleteDocumentDatabaseArgs";
import { DocumentDatabaseService } from "../documentDatabase.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => DocumentDatabase)
export class DocumentDatabaseResolverBase {
  constructor(
    protected readonly service: DocumentDatabaseService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "DocumentDatabase",
    action: "read",
    possession: "any",
  })
  async _documentDatabasesMeta(
    @graphql.Args() args: DocumentDatabaseCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [DocumentDatabase])
  @nestAccessControl.UseRoles({
    resource: "DocumentDatabase",
    action: "read",
    possession: "any",
  })
  async documentDatabases(
    @graphql.Args() args: DocumentDatabaseFindManyArgs
  ): Promise<DocumentDatabase[]> {
    return this.service.documentDatabases(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => DocumentDatabase, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "DocumentDatabase",
    action: "read",
    possession: "own",
  })
  async documentDatabase(
    @graphql.Args() args: DocumentDatabaseFindUniqueArgs
  ): Promise<DocumentDatabase | null> {
    const result = await this.service.documentDatabase(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => DocumentDatabase)
  @nestAccessControl.UseRoles({
    resource: "DocumentDatabase",
    action: "delete",
    possession: "any",
  })
  async deleteDocumentDatabase(
    @graphql.Args() args: DeleteDocumentDatabaseArgs
  ): Promise<DocumentDatabase | null> {
    try {
      return await this.service.deleteDocumentDatabase(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
