/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DocumentDatabaseService } from "../documentDatabase.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DocumentDatabaseCreateInput } from "./DocumentDatabaseCreateInput";
import { DocumentDatabase } from "./DocumentDatabase";
import { DocumentDatabaseFindManyArgs } from "./DocumentDatabaseFindManyArgs";
import { DocumentDatabaseWhereUniqueInput } from "./DocumentDatabaseWhereUniqueInput";
import { DocumentDatabaseUpdateInput } from "./DocumentDatabaseUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DocumentDatabaseControllerBase {
  constructor(
    protected readonly service: DocumentDatabaseService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DocumentDatabase })
  @nestAccessControl.UseRoles({
    resource: "DocumentDatabase",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: DocumentDatabaseCreateInput,
  })
  async createDocumentDatabase(
    @common.Body() data: DocumentDatabaseCreateInput
  ): Promise<DocumentDatabase> {
    return await this.service.createDocumentDatabase({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DocumentDatabase] })
  @ApiNestedQuery(DocumentDatabaseFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DocumentDatabase",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async documentDatabases(
    @common.Req() request: Request
  ): Promise<DocumentDatabase[]> {
    const args = plainToClass(DocumentDatabaseFindManyArgs, request.query);
    return this.service.documentDatabases({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DocumentDatabase })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DocumentDatabase",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async documentDatabase(
    @common.Param() params: DocumentDatabaseWhereUniqueInput
  ): Promise<DocumentDatabase | null> {
    const result = await this.service.documentDatabase({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DocumentDatabase })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DocumentDatabase",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: DocumentDatabaseUpdateInput,
  })
  async updateDocumentDatabase(
    @common.Param() params: DocumentDatabaseWhereUniqueInput,
    @common.Body() data: DocumentDatabaseUpdateInput
  ): Promise<DocumentDatabase | null> {
    try {
      return await this.service.updateDocumentDatabase({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DocumentDatabase })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DocumentDatabase",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDocumentDatabase(
    @common.Param() params: DocumentDatabaseWhereUniqueInput
  ): Promise<DocumentDatabase | null> {
    try {
      return await this.service.deleteDocumentDatabase({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
