/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DigitalTwinSupportService } from "../digitalTwinSupport.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DigitalTwinSupportCreateInput } from "./DigitalTwinSupportCreateInput";
import { DigitalTwinSupport } from "./DigitalTwinSupport";
import { DigitalTwinSupportFindManyArgs } from "./DigitalTwinSupportFindManyArgs";
import { DigitalTwinSupportWhereUniqueInput } from "./DigitalTwinSupportWhereUniqueInput";
import { DigitalTwinSupportUpdateInput } from "./DigitalTwinSupportUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DigitalTwinSupportControllerBase {
  constructor(
    protected readonly service: DigitalTwinSupportService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DigitalTwinSupport })
  @nestAccessControl.UseRoles({
    resource: "DigitalTwinSupport",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDigitalTwinSupport(
    @common.Body() data: DigitalTwinSupportCreateInput
  ): Promise<DigitalTwinSupport> {
    return await this.service.createDigitalTwinSupport({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DigitalTwinSupport] })
  @ApiNestedQuery(DigitalTwinSupportFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DigitalTwinSupport",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async digitalTwinSupports(
    @common.Req() request: Request
  ): Promise<DigitalTwinSupport[]> {
    const args = plainToClass(DigitalTwinSupportFindManyArgs, request.query);
    return this.service.digitalTwinSupports({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DigitalTwinSupport })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DigitalTwinSupport",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async digitalTwinSupport(
    @common.Param() params: DigitalTwinSupportWhereUniqueInput
  ): Promise<DigitalTwinSupport | null> {
    const result = await this.service.digitalTwinSupport({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DigitalTwinSupport })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DigitalTwinSupport",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDigitalTwinSupport(
    @common.Param() params: DigitalTwinSupportWhereUniqueInput,
    @common.Body() data: DigitalTwinSupportUpdateInput
  ): Promise<DigitalTwinSupport | null> {
    try {
      return await this.service.updateDigitalTwinSupport({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DigitalTwinSupport })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DigitalTwinSupport",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDigitalTwinSupport(
    @common.Param() params: DigitalTwinSupportWhereUniqueInput
  ): Promise<DigitalTwinSupport | null> {
    try {
      return await this.service.deleteDigitalTwinSupport({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
