/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CrossPlatformDevelopmentService } from "../crossPlatformDevelopment.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CrossPlatformDevelopmentCreateInput } from "./CrossPlatformDevelopmentCreateInput";
import { CrossPlatformDevelopment } from "./CrossPlatformDevelopment";
import { CrossPlatformDevelopmentFindManyArgs } from "./CrossPlatformDevelopmentFindManyArgs";
import { CrossPlatformDevelopmentWhereUniqueInput } from "./CrossPlatformDevelopmentWhereUniqueInput";
import { CrossPlatformDevelopmentUpdateInput } from "./CrossPlatformDevelopmentUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CrossPlatformDevelopmentControllerBase {
  constructor(
    protected readonly service: CrossPlatformDevelopmentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CrossPlatformDevelopment })
  @nestAccessControl.UseRoles({
    resource: "CrossPlatformDevelopment",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createCrossPlatformDevelopment(
    @common.Body() data: CrossPlatformDevelopmentCreateInput
  ): Promise<CrossPlatformDevelopment> {
    return await this.service.createCrossPlatformDevelopment({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [CrossPlatformDevelopment] })
  @ApiNestedQuery(CrossPlatformDevelopmentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CrossPlatformDevelopment",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async crossPlatformDevelopments(
    @common.Req() request: Request
  ): Promise<CrossPlatformDevelopment[]> {
    const args = plainToClass(
      CrossPlatformDevelopmentFindManyArgs,
      request.query
    );
    return this.service.crossPlatformDevelopments({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CrossPlatformDevelopment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CrossPlatformDevelopment",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async crossPlatformDevelopment(
    @common.Param() params: CrossPlatformDevelopmentWhereUniqueInput
  ): Promise<CrossPlatformDevelopment | null> {
    const result = await this.service.crossPlatformDevelopment({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CrossPlatformDevelopment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CrossPlatformDevelopment",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateCrossPlatformDevelopment(
    @common.Param() params: CrossPlatformDevelopmentWhereUniqueInput,
    @common.Body() data: CrossPlatformDevelopmentUpdateInput
  ): Promise<CrossPlatformDevelopment | null> {
    try {
      return await this.service.updateCrossPlatformDevelopment({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CrossPlatformDevelopment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CrossPlatformDevelopment",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCrossPlatformDevelopment(
    @common.Param() params: CrossPlatformDevelopmentWhereUniqueInput
  ): Promise<CrossPlatformDevelopment | null> {
    try {
      return await this.service.deleteCrossPlatformDevelopment({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
