/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { WorkflowBuilders } from "./WorkflowBuilders";
import { WorkflowBuildersCountArgs } from "./WorkflowBuildersCountArgs";
import { WorkflowBuildersFindManyArgs } from "./WorkflowBuildersFindManyArgs";
import { WorkflowBuildersFindUniqueArgs } from "./WorkflowBuildersFindUniqueArgs";
import { DeleteWorkflowBuildersArgs } from "./DeleteWorkflowBuildersArgs";
import { WorkflowBuildersService } from "../workflowBuilders.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => WorkflowBuilders)
export class WorkflowBuildersResolverBase {
  constructor(
    protected readonly service: WorkflowBuildersService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "WorkflowBuilders",
    action: "read",
    possession: "any",
  })
  async _workflowBuildersItemsMeta(
    @graphql.Args() args: WorkflowBuildersCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [WorkflowBuilders])
  @nestAccessControl.UseRoles({
    resource: "WorkflowBuilders",
    action: "read",
    possession: "any",
  })
  async workflowBuildersItems(
    @graphql.Args() args: WorkflowBuildersFindManyArgs
  ): Promise<WorkflowBuilders[]> {
    return this.service.workflowBuildersItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => WorkflowBuilders, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "WorkflowBuilders",
    action: "read",
    possession: "own",
  })
  async workflowBuilders(
    @graphql.Args() args: WorkflowBuildersFindUniqueArgs
  ): Promise<WorkflowBuilders | null> {
    const result = await this.service.workflowBuilders(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => WorkflowBuilders)
  @nestAccessControl.UseRoles({
    resource: "WorkflowBuilders",
    action: "delete",
    possession: "any",
  })
  async deleteWorkflowBuilders(
    @graphql.Args() args: DeleteWorkflowBuildersArgs
  ): Promise<WorkflowBuilders | null> {
    try {
      return await this.service.deleteWorkflowBuilders(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
