/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { WorkflowBuildersService } from "../workflowBuilders.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { WorkflowBuildersCreateInput } from "./WorkflowBuildersCreateInput";
import { WorkflowBuilders } from "./WorkflowBuilders";
import { WorkflowBuildersFindManyArgs } from "./WorkflowBuildersFindManyArgs";
import { WorkflowBuildersWhereUniqueInput } from "./WorkflowBuildersWhereUniqueInput";
import { WorkflowBuildersUpdateInput } from "./WorkflowBuildersUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class WorkflowBuildersControllerBase {
  constructor(
    protected readonly service: WorkflowBuildersService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: WorkflowBuilders })
  @nestAccessControl.UseRoles({
    resource: "WorkflowBuilders",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createWorkflowBuilders(
    @common.Body() data: WorkflowBuildersCreateInput
  ): Promise<WorkflowBuilders> {
    return await this.service.createWorkflowBuilders({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [WorkflowBuilders] })
  @ApiNestedQuery(WorkflowBuildersFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "WorkflowBuilders",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async workflowBuildersItems(
    @common.Req() request: Request
  ): Promise<WorkflowBuilders[]> {
    const args = plainToClass(WorkflowBuildersFindManyArgs, request.query);
    return this.service.workflowBuildersItems({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: WorkflowBuilders })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WorkflowBuilders",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async workflowBuilders(
    @common.Param() params: WorkflowBuildersWhereUniqueInput
  ): Promise<WorkflowBuilders | null> {
    const result = await this.service.workflowBuilders({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: WorkflowBuilders })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WorkflowBuilders",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateWorkflowBuilders(
    @common.Param() params: WorkflowBuildersWhereUniqueInput,
    @common.Body() data: WorkflowBuildersUpdateInput
  ): Promise<WorkflowBuilders | null> {
    try {
      return await this.service.updateWorkflowBuilders({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: WorkflowBuilders })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WorkflowBuilders",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteWorkflowBuilders(
    @common.Param() params: WorkflowBuildersWhereUniqueInput
  ): Promise<WorkflowBuilders | null> {
    try {
      return await this.service.deleteWorkflowBuilders({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
