/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  PersonalizedUserJourneys as PrismaPersonalizedUserJourneys,
} from "@prisma/client";

export class PersonalizedUserJourneysServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.PersonalizedUserJourneysCountArgs, "select">
  ): Promise<number> {
    return this.prisma.personalizedUserJourneys.count(args);
  }

  async personalizedUserJourneysItems(
    args: Prisma.PersonalizedUserJourneysFindManyArgs
  ): Promise<PrismaPersonalizedUserJourneys[]> {
    return this.prisma.personalizedUserJourneys.findMany(args);
  }
  async personalizedUserJourneys(
    args: Prisma.PersonalizedUserJourneysFindUniqueArgs
  ): Promise<PrismaPersonalizedUserJourneys | null> {
    return this.prisma.personalizedUserJourneys.findUnique(args);
  }
  async createPersonalizedUserJourneys(
    args: Prisma.PersonalizedUserJourneysCreateArgs
  ): Promise<PrismaPersonalizedUserJourneys> {
    return this.prisma.personalizedUserJourneys.create(args);
  }
  async updatePersonalizedUserJourneys(
    args: Prisma.PersonalizedUserJourneysUpdateArgs
  ): Promise<PrismaPersonalizedUserJourneys> {
    return this.prisma.personalizedUserJourneys.update(args);
  }
  async deletePersonalizedUserJourneys(
    args: Prisma.PersonalizedUserJourneysDeleteArgs
  ): Promise<PrismaPersonalizedUserJourneys> {
    return this.prisma.personalizedUserJourneys.delete(args);
  }
}
