/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PersonalizedUserJourneysService } from "../personalizedUserJourneys.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PersonalizedUserJourneysCreateInput } from "./PersonalizedUserJourneysCreateInput";
import { PersonalizedUserJourneys } from "./PersonalizedUserJourneys";
import { PersonalizedUserJourneysFindManyArgs } from "./PersonalizedUserJourneysFindManyArgs";
import { PersonalizedUserJourneysWhereUniqueInput } from "./PersonalizedUserJourneysWhereUniqueInput";
import { PersonalizedUserJourneysUpdateInput } from "./PersonalizedUserJourneysUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PersonalizedUserJourneysControllerBase {
  constructor(
    protected readonly service: PersonalizedUserJourneysService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PersonalizedUserJourneys })
  @nestAccessControl.UseRoles({
    resource: "PersonalizedUserJourneys",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPersonalizedUserJourneys(
    @common.Body() data: PersonalizedUserJourneysCreateInput
  ): Promise<PersonalizedUserJourneys> {
    return await this.service.createPersonalizedUserJourneys({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PersonalizedUserJourneys] })
  @ApiNestedQuery(PersonalizedUserJourneysFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PersonalizedUserJourneys",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async personalizedUserJourneysItems(
    @common.Req() request: Request
  ): Promise<PersonalizedUserJourneys[]> {
    const args = plainToClass(
      PersonalizedUserJourneysFindManyArgs,
      request.query
    );
    return this.service.personalizedUserJourneysItems({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PersonalizedUserJourneys })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PersonalizedUserJourneys",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async personalizedUserJourneys(
    @common.Param() params: PersonalizedUserJourneysWhereUniqueInput
  ): Promise<PersonalizedUserJourneys | null> {
    const result = await this.service.personalizedUserJourneys({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PersonalizedUserJourneys })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PersonalizedUserJourneys",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePersonalizedUserJourneys(
    @common.Param() params: PersonalizedUserJourneysWhereUniqueInput,
    @common.Body() data: PersonalizedUserJourneysUpdateInput
  ): Promise<PersonalizedUserJourneys | null> {
    try {
      return await this.service.updatePersonalizedUserJourneys({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PersonalizedUserJourneys })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PersonalizedUserJourneys",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePersonalizedUserJourneys(
    @common.Param() params: PersonalizedUserJourneysWhereUniqueInput
  ): Promise<PersonalizedUserJourneys | null> {
    try {
      return await this.service.deletePersonalizedUserJourneys({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
