/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { EdgeAnalytics } from "./EdgeAnalytics";
import { EdgeAnalyticsCountArgs } from "./EdgeAnalyticsCountArgs";
import { EdgeAnalyticsFindManyArgs } from "./EdgeAnalyticsFindManyArgs";
import { EdgeAnalyticsFindUniqueArgs } from "./EdgeAnalyticsFindUniqueArgs";
import { DeleteEdgeAnalyticsArgs } from "./DeleteEdgeAnalyticsArgs";
import { EdgeAnalyticsService } from "../edgeAnalytics.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => EdgeAnalytics)
export class EdgeAnalyticsResolverBase {
  constructor(
    protected readonly service: EdgeAnalyticsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "EdgeAnalytics",
    action: "read",
    possession: "any",
  })
  async _edgeAnalyticsItemsMeta(
    @graphql.Args() args: EdgeAnalyticsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [EdgeAnalytics])
  @nestAccessControl.UseRoles({
    resource: "EdgeAnalytics",
    action: "read",
    possession: "any",
  })
  async edgeAnalyticsItems(
    @graphql.Args() args: EdgeAnalyticsFindManyArgs
  ): Promise<EdgeAnalytics[]> {
    return this.service.edgeAnalyticsItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => EdgeAnalytics, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "EdgeAnalytics",
    action: "read",
    possession: "own",
  })
  async edgeAnalytics(
    @graphql.Args() args: EdgeAnalyticsFindUniqueArgs
  ): Promise<EdgeAnalytics | null> {
    const result = await this.service.edgeAnalytics(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => EdgeAnalytics)
  @nestAccessControl.UseRoles({
    resource: "EdgeAnalytics",
    action: "delete",
    possession: "any",
  })
  async deleteEdgeAnalytics(
    @graphql.Args() args: DeleteEdgeAnalyticsArgs
  ): Promise<EdgeAnalytics | null> {
    try {
      return await this.service.deleteEdgeAnalytics(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
