/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AutomatedCodeReview } from "./AutomatedCodeReview";
import { AutomatedCodeReviewCountArgs } from "./AutomatedCodeReviewCountArgs";
import { AutomatedCodeReviewFindManyArgs } from "./AutomatedCodeReviewFindManyArgs";
import { AutomatedCodeReviewFindUniqueArgs } from "./AutomatedCodeReviewFindUniqueArgs";
import { DeleteAutomatedCodeReviewArgs } from "./DeleteAutomatedCodeReviewArgs";
import { AutomatedCodeReviewService } from "../automatedCodeReview.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => AutomatedCodeReview)
export class AutomatedCodeReviewResolverBase {
  constructor(
    protected readonly service: AutomatedCodeReviewService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "AutomatedCodeReview",
    action: "read",
    possession: "any",
  })
  async _automatedCodeReviewsMeta(
    @graphql.Args() args: AutomatedCodeReviewCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [AutomatedCodeReview])
  @nestAccessControl.UseRoles({
    resource: "AutomatedCodeReview",
    action: "read",
    possession: "any",
  })
  async automatedCodeReviews(
    @graphql.Args() args: AutomatedCodeReviewFindManyArgs
  ): Promise<AutomatedCodeReview[]> {
    return this.service.automatedCodeReviews(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => AutomatedCodeReview, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "AutomatedCodeReview",
    action: "read",
    possession: "own",
  })
  async automatedCodeReview(
    @graphql.Args() args: AutomatedCodeReviewFindUniqueArgs
  ): Promise<AutomatedCodeReview | null> {
    const result = await this.service.automatedCodeReview(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AutomatedCodeReview)
  @nestAccessControl.UseRoles({
    resource: "AutomatedCodeReview",
    action: "delete",
    possession: "any",
  })
  async deleteAutomatedCodeReview(
    @graphql.Args() args: DeleteAutomatedCodeReviewArgs
  ): Promise<AutomatedCodeReview | null> {
    try {
      return await this.service.deleteAutomatedCodeReview(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
