/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { GreenHostingOptions } from "./GreenHostingOptions";
import { GreenHostingOptionsCountArgs } from "./GreenHostingOptionsCountArgs";
import { GreenHostingOptionsFindManyArgs } from "./GreenHostingOptionsFindManyArgs";
import { GreenHostingOptionsFindUniqueArgs } from "./GreenHostingOptionsFindUniqueArgs";
import { DeleteGreenHostingOptionsArgs } from "./DeleteGreenHostingOptionsArgs";
import { GreenHostingOptionsService } from "../greenHostingOptions.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => GreenHostingOptions)
export class GreenHostingOptionsResolverBase {
  constructor(
    protected readonly service: GreenHostingOptionsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "GreenHostingOptions",
    action: "read",
    possession: "any",
  })
  async _greenHostingOptionsItemsMeta(
    @graphql.Args() args: GreenHostingOptionsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [GreenHostingOptions])
  @nestAccessControl.UseRoles({
    resource: "GreenHostingOptions",
    action: "read",
    possession: "any",
  })
  async greenHostingOptionsItems(
    @graphql.Args() args: GreenHostingOptionsFindManyArgs
  ): Promise<GreenHostingOptions[]> {
    return this.service.greenHostingOptionsItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => GreenHostingOptions, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "GreenHostingOptions",
    action: "read",
    possession: "own",
  })
  async greenHostingOptions(
    @graphql.Args() args: GreenHostingOptionsFindUniqueArgs
  ): Promise<GreenHostingOptions | null> {
    const result = await this.service.greenHostingOptions(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => GreenHostingOptions)
  @nestAccessControl.UseRoles({
    resource: "GreenHostingOptions",
    action: "delete",
    possession: "any",
  })
  async deleteGreenHostingOptions(
    @graphql.Args() args: DeleteGreenHostingOptionsArgs
  ): Promise<GreenHostingOptions | null> {
    try {
      return await this.service.deleteGreenHostingOptions(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
