/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { EdgeComputingFunctions } from "./EdgeComputingFunctions";
import { EdgeComputingFunctionsCountArgs } from "./EdgeComputingFunctionsCountArgs";
import { EdgeComputingFunctionsFindManyArgs } from "./EdgeComputingFunctionsFindManyArgs";
import { EdgeComputingFunctionsFindUniqueArgs } from "./EdgeComputingFunctionsFindUniqueArgs";
import { DeleteEdgeComputingFunctionsArgs } from "./DeleteEdgeComputingFunctionsArgs";
import { EdgeComputingFunctionsService } from "../edgeComputingFunctions.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => EdgeComputingFunctions)
export class EdgeComputingFunctionsResolverBase {
  constructor(
    protected readonly service: EdgeComputingFunctionsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "EdgeComputingFunctions",
    action: "read",
    possession: "any",
  })
  async _edgeComputingFunctionsItemsMeta(
    @graphql.Args() args: EdgeComputingFunctionsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [EdgeComputingFunctions])
  @nestAccessControl.UseRoles({
    resource: "EdgeComputingFunctions",
    action: "read",
    possession: "any",
  })
  async edgeComputingFunctionsItems(
    @graphql.Args() args: EdgeComputingFunctionsFindManyArgs
  ): Promise<EdgeComputingFunctions[]> {
    return this.service.edgeComputingFunctionsItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => EdgeComputingFunctions, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "EdgeComputingFunctions",
    action: "read",
    possession: "own",
  })
  async edgeComputingFunctions(
    @graphql.Args() args: EdgeComputingFunctionsFindUniqueArgs
  ): Promise<EdgeComputingFunctions | null> {
    const result = await this.service.edgeComputingFunctions(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => EdgeComputingFunctions)
  @nestAccessControl.UseRoles({
    resource: "EdgeComputingFunctions",
    action: "delete",
    possession: "any",
  })
  async deleteEdgeComputingFunctions(
    @graphql.Args() args: DeleteEdgeComputingFunctionsArgs
  ): Promise<EdgeComputingFunctions | null> {
    try {
      return await this.service.deleteEdgeComputingFunctions(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
