/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { EdgeComputingFunctionsService } from "../edgeComputingFunctions.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { EdgeComputingFunctionsCreateInput } from "./EdgeComputingFunctionsCreateInput";
import { EdgeComputingFunctions } from "./EdgeComputingFunctions";
import { EdgeComputingFunctionsFindManyArgs } from "./EdgeComputingFunctionsFindManyArgs";
import { EdgeComputingFunctionsWhereUniqueInput } from "./EdgeComputingFunctionsWhereUniqueInput";
import { EdgeComputingFunctionsUpdateInput } from "./EdgeComputingFunctionsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class EdgeComputingFunctionsControllerBase {
  constructor(
    protected readonly service: EdgeComputingFunctionsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: EdgeComputingFunctions })
  @nestAccessControl.UseRoles({
    resource: "EdgeComputingFunctions",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createEdgeComputingFunctions(
    @common.Body() data: EdgeComputingFunctionsCreateInput
  ): Promise<EdgeComputingFunctions> {
    return await this.service.createEdgeComputingFunctions({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [EdgeComputingFunctions] })
  @ApiNestedQuery(EdgeComputingFunctionsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "EdgeComputingFunctions",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async edgeComputingFunctionsItems(
    @common.Req() request: Request
  ): Promise<EdgeComputingFunctions[]> {
    const args = plainToClass(
      EdgeComputingFunctionsFindManyArgs,
      request.query
    );
    return this.service.edgeComputingFunctionsItems({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: EdgeComputingFunctions })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EdgeComputingFunctions",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async edgeComputingFunctions(
    @common.Param() params: EdgeComputingFunctionsWhereUniqueInput
  ): Promise<EdgeComputingFunctions | null> {
    const result = await this.service.edgeComputingFunctions({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: EdgeComputingFunctions })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EdgeComputingFunctions",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateEdgeComputingFunctions(
    @common.Param() params: EdgeComputingFunctionsWhereUniqueInput,
    @common.Body() data: EdgeComputingFunctionsUpdateInput
  ): Promise<EdgeComputingFunctions | null> {
    try {
      return await this.service.updateEdgeComputingFunctions({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: EdgeComputingFunctions })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EdgeComputingFunctions",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteEdgeComputingFunctions(
    @common.Param() params: EdgeComputingFunctionsWhereUniqueInput
  ): Promise<EdgeComputingFunctions | null> {
    try {
      return await this.service.deleteEdgeComputingFunctions({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
