/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { BusinessIntelligenceDashboardsService } from "../businessIntelligenceDashboards.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { BusinessIntelligenceDashboardsCreateInput } from "./BusinessIntelligenceDashboardsCreateInput";
import { BusinessIntelligenceDashboards } from "./BusinessIntelligenceDashboards";
import { BusinessIntelligenceDashboardsFindManyArgs } from "./BusinessIntelligenceDashboardsFindManyArgs";
import { BusinessIntelligenceDashboardsWhereUniqueInput } from "./BusinessIntelligenceDashboardsWhereUniqueInput";
import { BusinessIntelligenceDashboardsUpdateInput } from "./BusinessIntelligenceDashboardsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class BusinessIntelligenceDashboardsControllerBase {
  constructor(
    protected readonly service: BusinessIntelligenceDashboardsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: BusinessIntelligenceDashboards })
  @nestAccessControl.UseRoles({
    resource: "BusinessIntelligenceDashboards",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: BusinessIntelligenceDashboardsCreateInput,
  })
  async createBusinessIntelligenceDashboards(
    @common.Body() data: BusinessIntelligenceDashboardsCreateInput
  ): Promise<BusinessIntelligenceDashboards> {
    return await this.service.createBusinessIntelligenceDashboards({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [BusinessIntelligenceDashboards] })
  @ApiNestedQuery(BusinessIntelligenceDashboardsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "BusinessIntelligenceDashboards",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async businessIntelligenceDashboardsItems(
    @common.Req() request: Request
  ): Promise<BusinessIntelligenceDashboards[]> {
    const args = plainToClass(
      BusinessIntelligenceDashboardsFindManyArgs,
      request.query
    );
    return this.service.businessIntelligenceDashboardsItems({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: BusinessIntelligenceDashboards })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BusinessIntelligenceDashboards",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async businessIntelligenceDashboards(
    @common.Param() params: BusinessIntelligenceDashboardsWhereUniqueInput
  ): Promise<BusinessIntelligenceDashboards | null> {
    const result = await this.service.businessIntelligenceDashboards({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: BusinessIntelligenceDashboards })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BusinessIntelligenceDashboards",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: BusinessIntelligenceDashboardsUpdateInput,
  })
  async updateBusinessIntelligenceDashboards(
    @common.Param() params: BusinessIntelligenceDashboardsWhereUniqueInput,
    @common.Body() data: BusinessIntelligenceDashboardsUpdateInput
  ): Promise<BusinessIntelligenceDashboards | null> {
    try {
      return await this.service.updateBusinessIntelligenceDashboards({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: BusinessIntelligenceDashboards })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BusinessIntelligenceDashboards",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteBusinessIntelligenceDashboards(
    @common.Param() params: BusinessIntelligenceDashboardsWhereUniqueInput
  ): Promise<BusinessIntelligenceDashboards | null> {
    try {
      return await this.service.deleteBusinessIntelligenceDashboards({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
