/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  BusinessIntelligenceDashboards as PrismaBusinessIntelligenceDashboards,
} from "@prisma/client";

export class BusinessIntelligenceDashboardsServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.BusinessIntelligenceDashboardsCountArgs, "select">
  ): Promise<number> {
    return this.prisma.businessIntelligenceDashboards.count(args);
  }

  async businessIntelligenceDashboardsItems(
    args: Prisma.BusinessIntelligenceDashboardsFindManyArgs
  ): Promise<PrismaBusinessIntelligenceDashboards[]> {
    return this.prisma.businessIntelligenceDashboards.findMany(args);
  }
  async businessIntelligenceDashboards(
    args: Prisma.BusinessIntelligenceDashboardsFindUniqueArgs
  ): Promise<PrismaBusinessIntelligenceDashboards | null> {
    return this.prisma.businessIntelligenceDashboards.findUnique(args);
  }
  async createBusinessIntelligenceDashboards(
    args: Prisma.BusinessIntelligenceDashboardsCreateArgs
  ): Promise<PrismaBusinessIntelligenceDashboards> {
    return this.prisma.businessIntelligenceDashboards.create(args);
  }
  async updateBusinessIntelligenceDashboards(
    args: Prisma.BusinessIntelligenceDashboardsUpdateArgs
  ): Promise<PrismaBusinessIntelligenceDashboards> {
    return this.prisma.businessIntelligenceDashboards.update(args);
  }
  async deleteBusinessIntelligenceDashboards(
    args: Prisma.BusinessIntelligenceDashboardsDeleteArgs
  ): Promise<PrismaBusinessIntelligenceDashboards> {
    return this.prisma.businessIntelligenceDashboards.delete(args);
  }
}
