/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PlatformSpecificOptimizationsService } from "../platformSpecificOptimizations.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PlatformSpecificOptimizationsCreateInput } from "./PlatformSpecificOptimizationsCreateInput";
import { PlatformSpecificOptimizations } from "./PlatformSpecificOptimizations";
import { PlatformSpecificOptimizationsFindManyArgs } from "./PlatformSpecificOptimizationsFindManyArgs";
import { PlatformSpecificOptimizationsWhereUniqueInput } from "./PlatformSpecificOptimizationsWhereUniqueInput";
import { PlatformSpecificOptimizationsUpdateInput } from "./PlatformSpecificOptimizationsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PlatformSpecificOptimizationsControllerBase {
  constructor(
    protected readonly service: PlatformSpecificOptimizationsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PlatformSpecificOptimizations })
  @nestAccessControl.UseRoles({
    resource: "PlatformSpecificOptimizations",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPlatformSpecificOptimizations(
    @common.Body() data: PlatformSpecificOptimizationsCreateInput
  ): Promise<PlatformSpecificOptimizations> {
    return await this.service.createPlatformSpecificOptimizations({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PlatformSpecificOptimizations] })
  @ApiNestedQuery(PlatformSpecificOptimizationsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PlatformSpecificOptimizations",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async platformSpecificOptimizationsItems(
    @common.Req() request: Request
  ): Promise<PlatformSpecificOptimizations[]> {
    const args = plainToClass(
      PlatformSpecificOptimizationsFindManyArgs,
      request.query
    );
    return this.service.platformSpecificOptimizationsItems({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PlatformSpecificOptimizations })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PlatformSpecificOptimizations",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async platformSpecificOptimizations(
    @common.Param() params: PlatformSpecificOptimizationsWhereUniqueInput
  ): Promise<PlatformSpecificOptimizations | null> {
    const result = await this.service.platformSpecificOptimizations({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PlatformSpecificOptimizations })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PlatformSpecificOptimizations",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePlatformSpecificOptimizations(
    @common.Param() params: PlatformSpecificOptimizationsWhereUniqueInput,
    @common.Body() data: PlatformSpecificOptimizationsUpdateInput
  ): Promise<PlatformSpecificOptimizations | null> {
    try {
      return await this.service.updatePlatformSpecificOptimizations({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PlatformSpecificOptimizations })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PlatformSpecificOptimizations",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePlatformSpecificOptimizations(
    @common.Param() params: PlatformSpecificOptimizationsWhereUniqueInput
  ): Promise<PlatformSpecificOptimizations | null> {
    try {
      return await this.service.deletePlatformSpecificOptimizations({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
