/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { IoTDataIngestion } from "./IoTDataIngestion";
import { IoTDataIngestionCountArgs } from "./IoTDataIngestionCountArgs";
import { IoTDataIngestionFindManyArgs } from "./IoTDataIngestionFindManyArgs";
import { IoTDataIngestionFindUniqueArgs } from "./IoTDataIngestionFindUniqueArgs";
import { DeleteIoTDataIngestionArgs } from "./DeleteIoTDataIngestionArgs";
import { IoTDataIngestionService } from "../ioTDataIngestion.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => IoTDataIngestion)
export class IoTDataIngestionResolverBase {
  constructor(
    protected readonly service: IoTDataIngestionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "IoTDataIngestion",
    action: "read",
    possession: "any",
  })
  async _ioTDataIngestionsMeta(
    @graphql.Args() args: IoTDataIngestionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [IoTDataIngestion])
  @nestAccessControl.UseRoles({
    resource: "IoTDataIngestion",
    action: "read",
    possession: "any",
  })
  async ioTDataIngestions(
    @graphql.Args() args: IoTDataIngestionFindManyArgs
  ): Promise<IoTDataIngestion[]> {
    return this.service.ioTDataIngestions(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => IoTDataIngestion, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "IoTDataIngestion",
    action: "read",
    possession: "own",
  })
  async ioTDataIngestion(
    @graphql.Args() args: IoTDataIngestionFindUniqueArgs
  ): Promise<IoTDataIngestion | null> {
    const result = await this.service.ioTDataIngestion(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => IoTDataIngestion)
  @nestAccessControl.UseRoles({
    resource: "IoTDataIngestion",
    action: "delete",
    possession: "any",
  })
  async deleteIoTDataIngestion(
    @graphql.Args() args: DeleteIoTDataIngestionArgs
  ): Promise<IoTDataIngestion | null> {
    try {
      return await this.service.deleteIoTDataIngestion(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
