/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  VoiceControlledDevelopment as PrismaVoiceControlledDevelopment,
} from "@prisma/client";

export class VoiceControlledDevelopmentServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.VoiceControlledDevelopmentCountArgs, "select">
  ): Promise<number> {
    return this.prisma.voiceControlledDevelopment.count(args);
  }

  async voiceControlledDevelopments(
    args: Prisma.VoiceControlledDevelopmentFindManyArgs
  ): Promise<PrismaVoiceControlledDevelopment[]> {
    return this.prisma.voiceControlledDevelopment.findMany(args);
  }
  async voiceControlledDevelopment(
    args: Prisma.VoiceControlledDevelopmentFindUniqueArgs
  ): Promise<PrismaVoiceControlledDevelopment | null> {
    return this.prisma.voiceControlledDevelopment.findUnique(args);
  }
  async createVoiceControlledDevelopment(
    args: Prisma.VoiceControlledDevelopmentCreateArgs
  ): Promise<PrismaVoiceControlledDevelopment> {
    return this.prisma.voiceControlledDevelopment.create(args);
  }
  async updateVoiceControlledDevelopment(
    args: Prisma.VoiceControlledDevelopmentUpdateArgs
  ): Promise<PrismaVoiceControlledDevelopment> {
    return this.prisma.voiceControlledDevelopment.update(args);
  }
  async deleteVoiceControlledDevelopment(
    args: Prisma.VoiceControlledDevelopmentDeleteArgs
  ): Promise<PrismaVoiceControlledDevelopment> {
    return this.prisma.voiceControlledDevelopment.delete(args);
  }
}
