/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { StatefulServerlessService } from "../statefulServerless.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { StatefulServerlessCreateInput } from "./StatefulServerlessCreateInput";
import { StatefulServerless } from "./StatefulServerless";
import { StatefulServerlessFindManyArgs } from "./StatefulServerlessFindManyArgs";
import { StatefulServerlessWhereUniqueInput } from "./StatefulServerlessWhereUniqueInput";
import { StatefulServerlessUpdateInput } from "./StatefulServerlessUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class StatefulServerlessControllerBase {
  constructor(
    protected readonly service: StatefulServerlessService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: StatefulServerless })
  @nestAccessControl.UseRoles({
    resource: "StatefulServerless",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createStatefulServerless(
    @common.Body() data: StatefulServerlessCreateInput
  ): Promise<StatefulServerless> {
    return await this.service.createStatefulServerless({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [StatefulServerless] })
  @ApiNestedQuery(StatefulServerlessFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "StatefulServerless",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async statefulServerlesses(
    @common.Req() request: Request
  ): Promise<StatefulServerless[]> {
    const args = plainToClass(StatefulServerlessFindManyArgs, request.query);
    return this.service.statefulServerlesses({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: StatefulServerless })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "StatefulServerless",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async statefulServerless(
    @common.Param() params: StatefulServerlessWhereUniqueInput
  ): Promise<StatefulServerless | null> {
    const result = await this.service.statefulServerless({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: StatefulServerless })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "StatefulServerless",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateStatefulServerless(
    @common.Param() params: StatefulServerlessWhereUniqueInput,
    @common.Body() data: StatefulServerlessUpdateInput
  ): Promise<StatefulServerless | null> {
    try {
      return await this.service.updateStatefulServerless({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: StatefulServerless })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "StatefulServerless",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteStatefulServerless(
    @common.Param() params: StatefulServerlessWhereUniqueInput
  ): Promise<StatefulServerless | null> {
    try {
      return await this.service.deleteStatefulServerless({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
