/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { HomomorphicEncryptionService } from "../homomorphicEncryption.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { HomomorphicEncryptionCreateInput } from "./HomomorphicEncryptionCreateInput";
import { HomomorphicEncryption } from "./HomomorphicEncryption";
import { HomomorphicEncryptionFindManyArgs } from "./HomomorphicEncryptionFindManyArgs";
import { HomomorphicEncryptionWhereUniqueInput } from "./HomomorphicEncryptionWhereUniqueInput";
import { HomomorphicEncryptionUpdateInput } from "./HomomorphicEncryptionUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class HomomorphicEncryptionControllerBase {
  constructor(
    protected readonly service: HomomorphicEncryptionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: HomomorphicEncryption })
  @nestAccessControl.UseRoles({
    resource: "HomomorphicEncryption",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: HomomorphicEncryptionCreateInput,
  })
  async createHomomorphicEncryption(
    @common.Body() data: HomomorphicEncryptionCreateInput
  ): Promise<HomomorphicEncryption> {
    return await this.service.createHomomorphicEncryption({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [HomomorphicEncryption] })
  @ApiNestedQuery(HomomorphicEncryptionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "HomomorphicEncryption",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async homomorphicEncryptions(
    @common.Req() request: Request
  ): Promise<HomomorphicEncryption[]> {
    const args = plainToClass(HomomorphicEncryptionFindManyArgs, request.query);
    return this.service.homomorphicEncryptions({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: HomomorphicEncryption })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HomomorphicEncryption",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async homomorphicEncryption(
    @common.Param() params: HomomorphicEncryptionWhereUniqueInput
  ): Promise<HomomorphicEncryption | null> {
    const result = await this.service.homomorphicEncryption({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: HomomorphicEncryption })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HomomorphicEncryption",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: HomomorphicEncryptionUpdateInput,
  })
  async updateHomomorphicEncryption(
    @common.Param() params: HomomorphicEncryptionWhereUniqueInput,
    @common.Body() data: HomomorphicEncryptionUpdateInput
  ): Promise<HomomorphicEncryption | null> {
    try {
      return await this.service.updateHomomorphicEncryption({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: HomomorphicEncryption })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HomomorphicEncryption",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteHomomorphicEncryption(
    @common.Param() params: HomomorphicEncryptionWhereUniqueInput
  ): Promise<HomomorphicEncryption | null> {
    try {
      return await this.service.deleteHomomorphicEncryption({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
