/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AutomatedComplianceChecks } from "./AutomatedComplianceChecks";
import { AutomatedComplianceChecksCountArgs } from "./AutomatedComplianceChecksCountArgs";
import { AutomatedComplianceChecksFindManyArgs } from "./AutomatedComplianceChecksFindManyArgs";
import { AutomatedComplianceChecksFindUniqueArgs } from "./AutomatedComplianceChecksFindUniqueArgs";
import { DeleteAutomatedComplianceChecksArgs } from "./DeleteAutomatedComplianceChecksArgs";
import { AutomatedComplianceChecksService } from "../automatedComplianceChecks.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => AutomatedComplianceChecks)
export class AutomatedComplianceChecksResolverBase {
  constructor(
    protected readonly service: AutomatedComplianceChecksService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "AutomatedComplianceChecks",
    action: "read",
    possession: "any",
  })
  async _automatedComplianceChecksItemsMeta(
    @graphql.Args() args: AutomatedComplianceChecksCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [AutomatedComplianceChecks])
  @nestAccessControl.UseRoles({
    resource: "AutomatedComplianceChecks",
    action: "read",
    possession: "any",
  })
  async automatedComplianceChecksItems(
    @graphql.Args() args: AutomatedComplianceChecksFindManyArgs
  ): Promise<AutomatedComplianceChecks[]> {
    return this.service.automatedComplianceChecksItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => AutomatedComplianceChecks, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "AutomatedComplianceChecks",
    action: "read",
    possession: "own",
  })
  async automatedComplianceChecks(
    @graphql.Args() args: AutomatedComplianceChecksFindUniqueArgs
  ): Promise<AutomatedComplianceChecks | null> {
    const result = await this.service.automatedComplianceChecks(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AutomatedComplianceChecks)
  @nestAccessControl.UseRoles({
    resource: "AutomatedComplianceChecks",
    action: "delete",
    possession: "any",
  })
  async deleteAutomatedComplianceChecks(
    @graphql.Args() args: DeleteAutomatedComplianceChecksArgs
  ): Promise<AutomatedComplianceChecks | null> {
    try {
      return await this.service.deleteAutomatedComplianceChecks(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
