/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  MultiLanguageRuntimeEnvironment as PrismaMultiLanguageRuntimeEnvironment,
} from "@prisma/client";

export class MultiLanguageRuntimeEnvironmentServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.MultiLanguageRuntimeEnvironmentCountArgs, "select">
  ): Promise<number> {
    return this.prisma.multiLanguageRuntimeEnvironment.count(args);
  }

  async multiLanguageRuntimeEnvironments(
    args: Prisma.MultiLanguageRuntimeEnvironmentFindManyArgs
  ): Promise<PrismaMultiLanguageRuntimeEnvironment[]> {
    return this.prisma.multiLanguageRuntimeEnvironment.findMany(args);
  }
  async multiLanguageRuntimeEnvironment(
    args: Prisma.MultiLanguageRuntimeEnvironmentFindUniqueArgs
  ): Promise<PrismaMultiLanguageRuntimeEnvironment | null> {
    return this.prisma.multiLanguageRuntimeEnvironment.findUnique(args);
  }
  async createMultiLanguageRuntimeEnvironment(
    args: Prisma.MultiLanguageRuntimeEnvironmentCreateArgs
  ): Promise<PrismaMultiLanguageRuntimeEnvironment> {
    return this.prisma.multiLanguageRuntimeEnvironment.create(args);
  }
  async updateMultiLanguageRuntimeEnvironment(
    args: Prisma.MultiLanguageRuntimeEnvironmentUpdateArgs
  ): Promise<PrismaMultiLanguageRuntimeEnvironment> {
    return this.prisma.multiLanguageRuntimeEnvironment.update(args);
  }
  async deleteMultiLanguageRuntimeEnvironment(
    args: Prisma.MultiLanguageRuntimeEnvironmentDeleteArgs
  ): Promise<PrismaMultiLanguageRuntimeEnvironment> {
    return this.prisma.multiLanguageRuntimeEnvironment.delete(args);
  }
}
