/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PasswordlessAuthenticationService } from "../passwordlessAuthentication.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PasswordlessAuthenticationCreateInput } from "./PasswordlessAuthenticationCreateInput";
import { PasswordlessAuthentication } from "./PasswordlessAuthentication";
import { PasswordlessAuthenticationFindManyArgs } from "./PasswordlessAuthenticationFindManyArgs";
import { PasswordlessAuthenticationWhereUniqueInput } from "./PasswordlessAuthenticationWhereUniqueInput";
import { PasswordlessAuthenticationUpdateInput } from "./PasswordlessAuthenticationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PasswordlessAuthenticationControllerBase {
  constructor(
    protected readonly service: PasswordlessAuthenticationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PasswordlessAuthentication })
  @nestAccessControl.UseRoles({
    resource: "PasswordlessAuthentication",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPasswordlessAuthentication(
    @common.Body() data: PasswordlessAuthenticationCreateInput
  ): Promise<PasswordlessAuthentication> {
    return await this.service.createPasswordlessAuthentication({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PasswordlessAuthentication] })
  @ApiNestedQuery(PasswordlessAuthenticationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PasswordlessAuthentication",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async passwordlessAuthentications(
    @common.Req() request: Request
  ): Promise<PasswordlessAuthentication[]> {
    const args = plainToClass(
      PasswordlessAuthenticationFindManyArgs,
      request.query
    );
    return this.service.passwordlessAuthentications({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PasswordlessAuthentication })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PasswordlessAuthentication",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async passwordlessAuthentication(
    @common.Param() params: PasswordlessAuthenticationWhereUniqueInput
  ): Promise<PasswordlessAuthentication | null> {
    const result = await this.service.passwordlessAuthentication({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PasswordlessAuthentication })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PasswordlessAuthentication",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePasswordlessAuthentication(
    @common.Param() params: PasswordlessAuthenticationWhereUniqueInput,
    @common.Body() data: PasswordlessAuthenticationUpdateInput
  ): Promise<PasswordlessAuthentication | null> {
    try {
      return await this.service.updatePasswordlessAuthentication({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PasswordlessAuthentication })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PasswordlessAuthentication",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePasswordlessAuthentication(
    @common.Param() params: PasswordlessAuthenticationWhereUniqueInput
  ): Promise<PasswordlessAuthentication | null> {
    try {
      return await this.service.deletePasswordlessAuthentication({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
