/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ContinuousLearningService } from "../continuousLearning.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ContinuousLearningCreateInput } from "./ContinuousLearningCreateInput";
import { ContinuousLearning } from "./ContinuousLearning";
import { ContinuousLearningFindManyArgs } from "./ContinuousLearningFindManyArgs";
import { ContinuousLearningWhereUniqueInput } from "./ContinuousLearningWhereUniqueInput";
import { ContinuousLearningUpdateInput } from "./ContinuousLearningUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ContinuousLearningControllerBase {
  constructor(
    protected readonly service: ContinuousLearningService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ContinuousLearning })
  @nestAccessControl.UseRoles({
    resource: "ContinuousLearning",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createContinuousLearning(
    @common.Body() data: ContinuousLearningCreateInput
  ): Promise<ContinuousLearning> {
    return await this.service.createContinuousLearning({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ContinuousLearning] })
  @ApiNestedQuery(ContinuousLearningFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ContinuousLearning",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async continuousLearnings(
    @common.Req() request: Request
  ): Promise<ContinuousLearning[]> {
    const args = plainToClass(ContinuousLearningFindManyArgs, request.query);
    return this.service.continuousLearnings({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ContinuousLearning })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ContinuousLearning",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async continuousLearning(
    @common.Param() params: ContinuousLearningWhereUniqueInput
  ): Promise<ContinuousLearning | null> {
    const result = await this.service.continuousLearning({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ContinuousLearning })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ContinuousLearning",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateContinuousLearning(
    @common.Param() params: ContinuousLearningWhereUniqueInput,
    @common.Body() data: ContinuousLearningUpdateInput
  ): Promise<ContinuousLearning | null> {
    try {
      return await this.service.updateContinuousLearning({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ContinuousLearning })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ContinuousLearning",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteContinuousLearning(
    @common.Param() params: ContinuousLearningWhereUniqueInput
  ): Promise<ContinuousLearning | null> {
    try {
      return await this.service.deleteContinuousLearning({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
