/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AutoMl } from "./AutoMl";
import { AutoMlCountArgs } from "./AutoMlCountArgs";
import { AutoMlFindManyArgs } from "./AutoMlFindManyArgs";
import { AutoMlFindUniqueArgs } from "./AutoMlFindUniqueArgs";
import { DeleteAutoMlArgs } from "./DeleteAutoMlArgs";
import { AutoMlService } from "../autoMl.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => AutoMl)
export class AutoMlResolverBase {
  constructor(
    protected readonly service: AutoMlService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "AutoMl",
    action: "read",
    possession: "any",
  })
  async _autoMlsMeta(
    @graphql.Args() args: AutoMlCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [AutoMl])
  @nestAccessControl.UseRoles({
    resource: "AutoMl",
    action: "read",
    possession: "any",
  })
  async autoMls(@graphql.Args() args: AutoMlFindManyArgs): Promise<AutoMl[]> {
    return this.service.autoMls(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => AutoMl, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "AutoMl",
    action: "read",
    possession: "own",
  })
  async autoMl(
    @graphql.Args() args: AutoMlFindUniqueArgs
  ): Promise<AutoMl | null> {
    const result = await this.service.autoMl(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AutoMl)
  @nestAccessControl.UseRoles({
    resource: "AutoMl",
    action: "delete",
    possession: "any",
  })
  async deleteAutoMl(
    @graphql.Args() args: DeleteAutoMlArgs
  ): Promise<AutoMl | null> {
    try {
      return await this.service.deleteAutoMl(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
