/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { MultiModelDatabaseService } from "../multiModelDatabase.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MultiModelDatabaseCreateInput } from "./MultiModelDatabaseCreateInput";
import { MultiModelDatabase } from "./MultiModelDatabase";
import { MultiModelDatabaseFindManyArgs } from "./MultiModelDatabaseFindManyArgs";
import { MultiModelDatabaseWhereUniqueInput } from "./MultiModelDatabaseWhereUniqueInput";
import { MultiModelDatabaseUpdateInput } from "./MultiModelDatabaseUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MultiModelDatabaseControllerBase {
  constructor(
    protected readonly service: MultiModelDatabaseService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: MultiModelDatabase })
  @nestAccessControl.UseRoles({
    resource: "MultiModelDatabase",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: MultiModelDatabaseCreateInput,
  })
  async createMultiModelDatabase(
    @common.Body() data: MultiModelDatabaseCreateInput
  ): Promise<MultiModelDatabase> {
    return await this.service.createMultiModelDatabase({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [MultiModelDatabase] })
  @ApiNestedQuery(MultiModelDatabaseFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "MultiModelDatabase",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async multiModelDatabases(
    @common.Req() request: Request
  ): Promise<MultiModelDatabase[]> {
    const args = plainToClass(MultiModelDatabaseFindManyArgs, request.query);
    return this.service.multiModelDatabases({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: MultiModelDatabase })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MultiModelDatabase",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async multiModelDatabase(
    @common.Param() params: MultiModelDatabaseWhereUniqueInput
  ): Promise<MultiModelDatabase | null> {
    const result = await this.service.multiModelDatabase({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: MultiModelDatabase })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MultiModelDatabase",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: MultiModelDatabaseUpdateInput,
  })
  async updateMultiModelDatabase(
    @common.Param() params: MultiModelDatabaseWhereUniqueInput,
    @common.Body() data: MultiModelDatabaseUpdateInput
  ): Promise<MultiModelDatabase | null> {
    try {
      return await this.service.updateMultiModelDatabase({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: MultiModelDatabase })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MultiModelDatabase",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteMultiModelDatabase(
    @common.Param() params: MultiModelDatabaseWhereUniqueInput
  ): Promise<MultiModelDatabase | null> {
    try {
      return await this.service.deleteMultiModelDatabase({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
