/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { NaturalLanguageToCode } from "./NaturalLanguageToCode";
import { NaturalLanguageToCodeCountArgs } from "./NaturalLanguageToCodeCountArgs";
import { NaturalLanguageToCodeFindManyArgs } from "./NaturalLanguageToCodeFindManyArgs";
import { NaturalLanguageToCodeFindUniqueArgs } from "./NaturalLanguageToCodeFindUniqueArgs";
import { DeleteNaturalLanguageToCodeArgs } from "./DeleteNaturalLanguageToCodeArgs";
import { NaturalLanguageToCodeService } from "../naturalLanguageToCode.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => NaturalLanguageToCode)
export class NaturalLanguageToCodeResolverBase {
  constructor(
    protected readonly service: NaturalLanguageToCodeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "NaturalLanguageToCode",
    action: "read",
    possession: "any",
  })
  async _naturalLanguageToCodesMeta(
    @graphql.Args() args: NaturalLanguageToCodeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [NaturalLanguageToCode])
  @nestAccessControl.UseRoles({
    resource: "NaturalLanguageToCode",
    action: "read",
    possession: "any",
  })
  async naturalLanguageToCodes(
    @graphql.Args() args: NaturalLanguageToCodeFindManyArgs
  ): Promise<NaturalLanguageToCode[]> {
    return this.service.naturalLanguageToCodes(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => NaturalLanguageToCode, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "NaturalLanguageToCode",
    action: "read",
    possession: "own",
  })
  async naturalLanguageToCode(
    @graphql.Args() args: NaturalLanguageToCodeFindUniqueArgs
  ): Promise<NaturalLanguageToCode | null> {
    const result = await this.service.naturalLanguageToCode(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => NaturalLanguageToCode)
  @nestAccessControl.UseRoles({
    resource: "NaturalLanguageToCode",
    action: "delete",
    possession: "any",
  })
  async deleteNaturalLanguageToCode(
    @graphql.Args() args: DeleteNaturalLanguageToCodeArgs
  ): Promise<NaturalLanguageToCode | null> {
    try {
      return await this.service.deleteNaturalLanguageToCode(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
