/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PerformanceTuning } from "./PerformanceTuning";
import { PerformanceTuningCountArgs } from "./PerformanceTuningCountArgs";
import { PerformanceTuningFindManyArgs } from "./PerformanceTuningFindManyArgs";
import { PerformanceTuningFindUniqueArgs } from "./PerformanceTuningFindUniqueArgs";
import { DeletePerformanceTuningArgs } from "./DeletePerformanceTuningArgs";
import { PerformanceTuningService } from "../performanceTuning.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => PerformanceTuning)
export class PerformanceTuningResolverBase {
  constructor(
    protected readonly service: PerformanceTuningService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "PerformanceTuning",
    action: "read",
    possession: "any",
  })
  async _performanceTuningsMeta(
    @graphql.Args() args: PerformanceTuningCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [PerformanceTuning])
  @nestAccessControl.UseRoles({
    resource: "PerformanceTuning",
    action: "read",
    possession: "any",
  })
  async performanceTunings(
    @graphql.Args() args: PerformanceTuningFindManyArgs
  ): Promise<PerformanceTuning[]> {
    return this.service.performanceTunings(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => PerformanceTuning, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PerformanceTuning",
    action: "read",
    possession: "own",
  })
  async performanceTuning(
    @graphql.Args() args: PerformanceTuningFindUniqueArgs
  ): Promise<PerformanceTuning | null> {
    const result = await this.service.performanceTuning(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PerformanceTuning)
  @nestAccessControl.UseRoles({
    resource: "PerformanceTuning",
    action: "delete",
    possession: "any",
  })
  async deletePerformanceTuning(
    @graphql.Args() args: DeletePerformanceTuningArgs
  ): Promise<PerformanceTuning | null> {
    try {
      return await this.service.deletePerformanceTuning(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
