/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  SmartContractDevelopment as PrismaSmartContractDevelopment,
} from "@prisma/client";

export class SmartContractDevelopmentServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.SmartContractDevelopmentCountArgs, "select">
  ): Promise<number> {
    return this.prisma.smartContractDevelopment.count(args);
  }

  async smartContractDevelopments(
    args: Prisma.SmartContractDevelopmentFindManyArgs
  ): Promise<PrismaSmartContractDevelopment[]> {
    return this.prisma.smartContractDevelopment.findMany(args);
  }
  async smartContractDevelopment(
    args: Prisma.SmartContractDevelopmentFindUniqueArgs
  ): Promise<PrismaSmartContractDevelopment | null> {
    return this.prisma.smartContractDevelopment.findUnique(args);
  }
  async createSmartContractDevelopment(
    args: Prisma.SmartContractDevelopmentCreateArgs
  ): Promise<PrismaSmartContractDevelopment> {
    return this.prisma.smartContractDevelopment.create(args);
  }
  async updateSmartContractDevelopment(
    args: Prisma.SmartContractDevelopmentUpdateArgs
  ): Promise<PrismaSmartContractDevelopment> {
    return this.prisma.smartContractDevelopment.update(args);
  }
  async deleteSmartContractDevelopment(
    args: Prisma.SmartContractDevelopmentDeleteArgs
  ): Promise<PrismaSmartContractDevelopment> {
    return this.prisma.smartContractDevelopment.delete(args);
  }
}
