/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ZeroTrustSecurity } from "./ZeroTrustSecurity";
import { ZeroTrustSecurityCountArgs } from "./ZeroTrustSecurityCountArgs";
import { ZeroTrustSecurityFindManyArgs } from "./ZeroTrustSecurityFindManyArgs";
import { ZeroTrustSecurityFindUniqueArgs } from "./ZeroTrustSecurityFindUniqueArgs";
import { DeleteZeroTrustSecurityArgs } from "./DeleteZeroTrustSecurityArgs";
import { ZeroTrustSecurityService } from "../zeroTrustSecurity.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ZeroTrustSecurity)
export class ZeroTrustSecurityResolverBase {
  constructor(
    protected readonly service: ZeroTrustSecurityService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ZeroTrustSecurity",
    action: "read",
    possession: "any",
  })
  async _zeroTrustSecuritiesMeta(
    @graphql.Args() args: ZeroTrustSecurityCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ZeroTrustSecurity])
  @nestAccessControl.UseRoles({
    resource: "ZeroTrustSecurity",
    action: "read",
    possession: "any",
  })
  async zeroTrustSecurities(
    @graphql.Args() args: ZeroTrustSecurityFindManyArgs
  ): Promise<ZeroTrustSecurity[]> {
    return this.service.zeroTrustSecurities(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ZeroTrustSecurity, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ZeroTrustSecurity",
    action: "read",
    possession: "own",
  })
  async zeroTrustSecurity(
    @graphql.Args() args: ZeroTrustSecurityFindUniqueArgs
  ): Promise<ZeroTrustSecurity | null> {
    const result = await this.service.zeroTrustSecurity(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ZeroTrustSecurity)
  @nestAccessControl.UseRoles({
    resource: "ZeroTrustSecurity",
    action: "delete",
    possession: "any",
  })
  async deleteZeroTrustSecurity(
    @graphql.Args() args: DeleteZeroTrustSecurityArgs
  ): Promise<ZeroTrustSecurity | null> {
    try {
      return await this.service.deleteZeroTrustSecurity(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
