/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AiDrivenIncidentResponseService } from "../aiDrivenIncidentResponse.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AiDrivenIncidentResponseCreateInput } from "./AiDrivenIncidentResponseCreateInput";
import { AiDrivenIncidentResponse } from "./AiDrivenIncidentResponse";
import { AiDrivenIncidentResponseFindManyArgs } from "./AiDrivenIncidentResponseFindManyArgs";
import { AiDrivenIncidentResponseWhereUniqueInput } from "./AiDrivenIncidentResponseWhereUniqueInput";
import { AiDrivenIncidentResponseUpdateInput } from "./AiDrivenIncidentResponseUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AiDrivenIncidentResponseControllerBase {
  constructor(
    protected readonly service: AiDrivenIncidentResponseService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AiDrivenIncidentResponse })
  @nestAccessControl.UseRoles({
    resource: "AiDrivenIncidentResponse",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: AiDrivenIncidentResponseCreateInput,
  })
  async createAiDrivenIncidentResponse(
    @common.Body() data: AiDrivenIncidentResponseCreateInput
  ): Promise<AiDrivenIncidentResponse> {
    return await this.service.createAiDrivenIncidentResponse({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AiDrivenIncidentResponse] })
  @ApiNestedQuery(AiDrivenIncidentResponseFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AiDrivenIncidentResponse",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async aiDrivenIncidentResponses(
    @common.Req() request: Request
  ): Promise<AiDrivenIncidentResponse[]> {
    const args = plainToClass(
      AiDrivenIncidentResponseFindManyArgs,
      request.query
    );
    return this.service.aiDrivenIncidentResponses({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AiDrivenIncidentResponse })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AiDrivenIncidentResponse",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async aiDrivenIncidentResponse(
    @common.Param() params: AiDrivenIncidentResponseWhereUniqueInput
  ): Promise<AiDrivenIncidentResponse | null> {
    const result = await this.service.aiDrivenIncidentResponse({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AiDrivenIncidentResponse })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AiDrivenIncidentResponse",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: AiDrivenIncidentResponseUpdateInput,
  })
  async updateAiDrivenIncidentResponse(
    @common.Param() params: AiDrivenIncidentResponseWhereUniqueInput,
    @common.Body() data: AiDrivenIncidentResponseUpdateInput
  ): Promise<AiDrivenIncidentResponse | null> {
    try {
      return await this.service.updateAiDrivenIncidentResponse({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AiDrivenIncidentResponse })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AiDrivenIncidentResponse",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAiDrivenIncidentResponse(
    @common.Param() params: AiDrivenIncidentResponseWhereUniqueInput
  ): Promise<AiDrivenIncidentResponse | null> {
    try {
      return await this.service.deleteAiDrivenIncidentResponse({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
