/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { GraphQlSupportService } from "../graphQlSupport.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { GraphQlSupportCreateInput } from "./GraphQlSupportCreateInput";
import { GraphQlSupport } from "./GraphQlSupport";
import { GraphQlSupportFindManyArgs } from "./GraphQlSupportFindManyArgs";
import { GraphQlSupportWhereUniqueInput } from "./GraphQlSupportWhereUniqueInput";
import { GraphQlSupportUpdateInput } from "./GraphQlSupportUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class GraphQlSupportControllerBase {
  constructor(
    protected readonly service: GraphQlSupportService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: GraphQlSupport })
  @nestAccessControl.UseRoles({
    resource: "GraphQlSupport",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createGraphQlSupport(
    @common.Body() data: GraphQlSupportCreateInput
  ): Promise<GraphQlSupport> {
    return await this.service.createGraphQlSupport({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [GraphQlSupport] })
  @ApiNestedQuery(GraphQlSupportFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "GraphQlSupport",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async graphQlSupports(
    @common.Req() request: Request
  ): Promise<GraphQlSupport[]> {
    const args = plainToClass(GraphQlSupportFindManyArgs, request.query);
    return this.service.graphQlSupports({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: GraphQlSupport })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "GraphQlSupport",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async graphQlSupport(
    @common.Param() params: GraphQlSupportWhereUniqueInput
  ): Promise<GraphQlSupport | null> {
    const result = await this.service.graphQlSupport({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: GraphQlSupport })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "GraphQlSupport",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateGraphQlSupport(
    @common.Param() params: GraphQlSupportWhereUniqueInput,
    @common.Body() data: GraphQlSupportUpdateInput
  ): Promise<GraphQlSupport | null> {
    try {
      return await this.service.updateGraphQlSupport({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: GraphQlSupport })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "GraphQlSupport",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteGraphQlSupport(
    @common.Param() params: GraphQlSupportWhereUniqueInput
  ): Promise<GraphQlSupport | null> {
    try {
      return await this.service.deleteGraphQlSupport({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
