/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ArAppPrototyping } from "./ArAppPrototyping";
import { ArAppPrototypingCountArgs } from "./ArAppPrototypingCountArgs";
import { ArAppPrototypingFindManyArgs } from "./ArAppPrototypingFindManyArgs";
import { ArAppPrototypingFindUniqueArgs } from "./ArAppPrototypingFindUniqueArgs";
import { DeleteArAppPrototypingArgs } from "./DeleteArAppPrototypingArgs";
import { ArAppPrototypingService } from "../arAppPrototyping.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ArAppPrototyping)
export class ArAppPrototypingResolverBase {
  constructor(
    protected readonly service: ArAppPrototypingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ArAppPrototyping",
    action: "read",
    possession: "any",
  })
  async _arAppPrototypingsMeta(
    @graphql.Args() args: ArAppPrototypingCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ArAppPrototyping])
  @nestAccessControl.UseRoles({
    resource: "ArAppPrototyping",
    action: "read",
    possession: "any",
  })
  async arAppPrototypings(
    @graphql.Args() args: ArAppPrototypingFindManyArgs
  ): Promise<ArAppPrototyping[]> {
    return this.service.arAppPrototypings(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ArAppPrototyping, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ArAppPrototyping",
    action: "read",
    possession: "own",
  })
  async arAppPrototyping(
    @graphql.Args() args: ArAppPrototypingFindUniqueArgs
  ): Promise<ArAppPrototyping | null> {
    const result = await this.service.arAppPrototyping(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ArAppPrototyping)
  @nestAccessControl.UseRoles({
    resource: "ArAppPrototyping",
    action: "delete",
    possession: "any",
  })
  async deleteArAppPrototyping(
    @graphql.Args() args: DeleteArAppPrototypingArgs
  ): Promise<ArAppPrototyping | null> {
    try {
      return await this.service.deleteArAppPrototyping(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
