/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserBehaviorModeling } from "./UserBehaviorModeling";
import { UserBehaviorModelingCountArgs } from "./UserBehaviorModelingCountArgs";
import { UserBehaviorModelingFindManyArgs } from "./UserBehaviorModelingFindManyArgs";
import { UserBehaviorModelingFindUniqueArgs } from "./UserBehaviorModelingFindUniqueArgs";
import { DeleteUserBehaviorModelingArgs } from "./DeleteUserBehaviorModelingArgs";
import { UserBehaviorModelingService } from "../userBehaviorModeling.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => UserBehaviorModeling)
export class UserBehaviorModelingResolverBase {
  constructor(
    protected readonly service: UserBehaviorModelingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "UserBehaviorModeling",
    action: "read",
    possession: "any",
  })
  async _userBehaviorModelingsMeta(
    @graphql.Args() args: UserBehaviorModelingCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [UserBehaviorModeling])
  @nestAccessControl.UseRoles({
    resource: "UserBehaviorModeling",
    action: "read",
    possession: "any",
  })
  async userBehaviorModelings(
    @graphql.Args() args: UserBehaviorModelingFindManyArgs
  ): Promise<UserBehaviorModeling[]> {
    return this.service.userBehaviorModelings(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => UserBehaviorModeling, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "UserBehaviorModeling",
    action: "read",
    possession: "own",
  })
  async userBehaviorModeling(
    @graphql.Args() args: UserBehaviorModelingFindUniqueArgs
  ): Promise<UserBehaviorModeling | null> {
    const result = await this.service.userBehaviorModeling(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => UserBehaviorModeling)
  @nestAccessControl.UseRoles({
    resource: "UserBehaviorModeling",
    action: "delete",
    possession: "any",
  })
  async deleteUserBehaviorModeling(
    @graphql.Args() args: DeleteUserBehaviorModelingArgs
  ): Promise<UserBehaviorModeling | null> {
    try {
      return await this.service.deleteUserBehaviorModeling(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
