/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DataLineageTrackingService } from "../dataLineageTracking.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DataLineageTrackingCreateInput } from "./DataLineageTrackingCreateInput";
import { DataLineageTracking } from "./DataLineageTracking";
import { DataLineageTrackingFindManyArgs } from "./DataLineageTrackingFindManyArgs";
import { DataLineageTrackingWhereUniqueInput } from "./DataLineageTrackingWhereUniqueInput";
import { DataLineageTrackingUpdateInput } from "./DataLineageTrackingUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DataLineageTrackingControllerBase {
  constructor(
    protected readonly service: DataLineageTrackingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DataLineageTracking })
  @nestAccessControl.UseRoles({
    resource: "DataLineageTracking",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: DataLineageTrackingCreateInput,
  })
  async createDataLineageTracking(
    @common.Body() data: DataLineageTrackingCreateInput
  ): Promise<DataLineageTracking> {
    return await this.service.createDataLineageTracking({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DataLineageTracking] })
  @ApiNestedQuery(DataLineageTrackingFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DataLineageTracking",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async dataLineageTrackings(
    @common.Req() request: Request
  ): Promise<DataLineageTracking[]> {
    const args = plainToClass(DataLineageTrackingFindManyArgs, request.query);
    return this.service.dataLineageTrackings({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DataLineageTracking })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DataLineageTracking",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async dataLineageTracking(
    @common.Param() params: DataLineageTrackingWhereUniqueInput
  ): Promise<DataLineageTracking | null> {
    const result = await this.service.dataLineageTracking({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DataLineageTracking })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DataLineageTracking",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: DataLineageTrackingUpdateInput,
  })
  async updateDataLineageTracking(
    @common.Param() params: DataLineageTrackingWhereUniqueInput,
    @common.Body() data: DataLineageTrackingUpdateInput
  ): Promise<DataLineageTracking | null> {
    try {
      return await this.service.updateDataLineageTracking({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DataLineageTracking })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DataLineageTracking",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDataLineageTracking(
    @common.Param() params: DataLineageTrackingWhereUniqueInput
  ): Promise<DataLineageTracking | null> {
    try {
      return await this.service.deleteDataLineageTracking({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
