/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DataLineageTracking } from "./DataLineageTracking";
import { DataLineageTrackingCountArgs } from "./DataLineageTrackingCountArgs";
import { DataLineageTrackingFindManyArgs } from "./DataLineageTrackingFindManyArgs";
import { DataLineageTrackingFindUniqueArgs } from "./DataLineageTrackingFindUniqueArgs";
import { DeleteDataLineageTrackingArgs } from "./DeleteDataLineageTrackingArgs";
import { DataLineageTrackingService } from "../dataLineageTracking.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => DataLineageTracking)
export class DataLineageTrackingResolverBase {
  constructor(
    protected readonly service: DataLineageTrackingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "DataLineageTracking",
    action: "read",
    possession: "any",
  })
  async _dataLineageTrackingsMeta(
    @graphql.Args() args: DataLineageTrackingCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [DataLineageTracking])
  @nestAccessControl.UseRoles({
    resource: "DataLineageTracking",
    action: "read",
    possession: "any",
  })
  async dataLineageTrackings(
    @graphql.Args() args: DataLineageTrackingFindManyArgs
  ): Promise<DataLineageTracking[]> {
    return this.service.dataLineageTrackings(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => DataLineageTracking, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "DataLineageTracking",
    action: "read",
    possession: "own",
  })
  async dataLineageTracking(
    @graphql.Args() args: DataLineageTrackingFindUniqueArgs
  ): Promise<DataLineageTracking | null> {
    const result = await this.service.dataLineageTracking(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => DataLineageTracking)
  @nestAccessControl.UseRoles({
    resource: "DataLineageTracking",
    action: "delete",
    possession: "any",
  })
  async deleteDataLineageTracking(
    @graphql.Args() args: DeleteDataLineageTrackingArgs
  ): Promise<DataLineageTracking | null> {
    try {
      return await this.service.deleteDataLineageTracking(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
