/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AutomatedPiiDetectionService } from "../automatedPiiDetection.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AutomatedPiiDetectionCreateInput } from "./AutomatedPiiDetectionCreateInput";
import { AutomatedPiiDetection } from "./AutomatedPiiDetection";
import { AutomatedPiiDetectionFindManyArgs } from "./AutomatedPiiDetectionFindManyArgs";
import { AutomatedPiiDetectionWhereUniqueInput } from "./AutomatedPiiDetectionWhereUniqueInput";
import { AutomatedPiiDetectionUpdateInput } from "./AutomatedPiiDetectionUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AutomatedPiiDetectionControllerBase {
  constructor(
    protected readonly service: AutomatedPiiDetectionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AutomatedPiiDetection })
  @nestAccessControl.UseRoles({
    resource: "AutomatedPiiDetection",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: AutomatedPiiDetectionCreateInput,
  })
  async createAutomatedPiiDetection(
    @common.Body() data: AutomatedPiiDetectionCreateInput
  ): Promise<AutomatedPiiDetection> {
    return await this.service.createAutomatedPiiDetection({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AutomatedPiiDetection] })
  @ApiNestedQuery(AutomatedPiiDetectionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AutomatedPiiDetection",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async automatedPiiDetections(
    @common.Req() request: Request
  ): Promise<AutomatedPiiDetection[]> {
    const args = plainToClass(AutomatedPiiDetectionFindManyArgs, request.query);
    return this.service.automatedPiiDetections({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AutomatedPiiDetection })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AutomatedPiiDetection",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async automatedPiiDetection(
    @common.Param() params: AutomatedPiiDetectionWhereUniqueInput
  ): Promise<AutomatedPiiDetection | null> {
    const result = await this.service.automatedPiiDetection({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AutomatedPiiDetection })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AutomatedPiiDetection",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: AutomatedPiiDetectionUpdateInput,
  })
  async updateAutomatedPiiDetection(
    @common.Param() params: AutomatedPiiDetectionWhereUniqueInput,
    @common.Body() data: AutomatedPiiDetectionUpdateInput
  ): Promise<AutomatedPiiDetection | null> {
    try {
      return await this.service.updateAutomatedPiiDetection({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AutomatedPiiDetection })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AutomatedPiiDetection",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAutomatedPiiDetection(
    @common.Param() params: AutomatedPiiDetectionWhereUniqueInput
  ): Promise<AutomatedPiiDetection | null> {
    try {
      return await this.service.deleteAutomatedPiiDetection({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
