/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { RealTimeTranslationService } from "../realTimeTranslation.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RealTimeTranslationCreateInput } from "./RealTimeTranslationCreateInput";
import { RealTimeTranslation } from "./RealTimeTranslation";
import { RealTimeTranslationFindManyArgs } from "./RealTimeTranslationFindManyArgs";
import { RealTimeTranslationWhereUniqueInput } from "./RealTimeTranslationWhereUniqueInput";
import { RealTimeTranslationUpdateInput } from "./RealTimeTranslationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RealTimeTranslationControllerBase {
  constructor(
    protected readonly service: RealTimeTranslationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: RealTimeTranslation })
  @nestAccessControl.UseRoles({
    resource: "RealTimeTranslation",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createRealTimeTranslation(
    @common.Body() data: RealTimeTranslationCreateInput
  ): Promise<RealTimeTranslation> {
    return await this.service.createRealTimeTranslation({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [RealTimeTranslation] })
  @ApiNestedQuery(RealTimeTranslationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "RealTimeTranslation",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async realTimeTranslations(
    @common.Req() request: Request
  ): Promise<RealTimeTranslation[]> {
    const args = plainToClass(RealTimeTranslationFindManyArgs, request.query);
    return this.service.realTimeTranslations({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: RealTimeTranslation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RealTimeTranslation",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async realTimeTranslation(
    @common.Param() params: RealTimeTranslationWhereUniqueInput
  ): Promise<RealTimeTranslation | null> {
    const result = await this.service.realTimeTranslation({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: RealTimeTranslation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RealTimeTranslation",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateRealTimeTranslation(
    @common.Param() params: RealTimeTranslationWhereUniqueInput,
    @common.Body() data: RealTimeTranslationUpdateInput
  ): Promise<RealTimeTranslation | null> {
    try {
      return await this.service.updateRealTimeTranslation({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: RealTimeTranslation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RealTimeTranslation",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteRealTimeTranslation(
    @common.Param() params: RealTimeTranslationWhereUniqueInput
  ): Promise<RealTimeTranslation | null> {
    try {
      return await this.service.deleteRealTimeTranslation({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
