/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ComplexEventProcessingService } from "../complexEventProcessing.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ComplexEventProcessingCreateInput } from "./ComplexEventProcessingCreateInput";
import { ComplexEventProcessing } from "./ComplexEventProcessing";
import { ComplexEventProcessingFindManyArgs } from "./ComplexEventProcessingFindManyArgs";
import { ComplexEventProcessingWhereUniqueInput } from "./ComplexEventProcessingWhereUniqueInput";
import { ComplexEventProcessingUpdateInput } from "./ComplexEventProcessingUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ComplexEventProcessingControllerBase {
  constructor(
    protected readonly service: ComplexEventProcessingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ComplexEventProcessing })
  @nestAccessControl.UseRoles({
    resource: "ComplexEventProcessing",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createComplexEventProcessing(
    @common.Body() data: ComplexEventProcessingCreateInput
  ): Promise<ComplexEventProcessing> {
    return await this.service.createComplexEventProcessing({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ComplexEventProcessing] })
  @ApiNestedQuery(ComplexEventProcessingFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ComplexEventProcessing",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async complexEventProcessings(
    @common.Req() request: Request
  ): Promise<ComplexEventProcessing[]> {
    const args = plainToClass(
      ComplexEventProcessingFindManyArgs,
      request.query
    );
    return this.service.complexEventProcessings({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ComplexEventProcessing })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ComplexEventProcessing",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async complexEventProcessing(
    @common.Param() params: ComplexEventProcessingWhereUniqueInput
  ): Promise<ComplexEventProcessing | null> {
    const result = await this.service.complexEventProcessing({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ComplexEventProcessing })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ComplexEventProcessing",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateComplexEventProcessing(
    @common.Param() params: ComplexEventProcessingWhereUniqueInput,
    @common.Body() data: ComplexEventProcessingUpdateInput
  ): Promise<ComplexEventProcessing | null> {
    try {
      return await this.service.updateComplexEventProcessing({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ComplexEventProcessing })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ComplexEventProcessing",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteComplexEventProcessing(
    @common.Param() params: ComplexEventProcessingWhereUniqueInput
  ): Promise<ComplexEventProcessing | null> {
    try {
      return await this.service.deleteComplexEventProcessing({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
